### ISSUE TITLE
bash issue?

### ISSUE THREAD

**Issue by 3keston** [dooklink/gbs-control#1]
Fresh install with Raspbian Version:December 2014, Release date:2014-12-24, Model B rev1

There appears to be a posix type error with bash. 

bash gbs-control.sh gives
gbs-control.sh: line 336: syntax error near unexpected token `)'

gbs-control.sh: line 336: ` leLioaUE=fi an./ -maxdepth60 -t"Typf |nd rt)

**Comment by dooklink** [comment]
Yes, I've done something odd. I tried to publish v0.2 last night and my 
zip package somehow got corrupted.
I don't know how this happened, but I'll try and fix it soon.

Regards,
Dooklink

**Comment by dooklink** [comment]
New v0.2 posted. zip corruption shouldn't happen again as I've disabled delta compression for zips and set them as binary in the git attributes.
