### ISSUE TITLE
bad path?

### ISSUE THREAD

**Issue by HBDK** [dooklink/gbs-control#3]
Shouldn't line 24 in GBS.conf be 
KEY_3+KEY_RIGHTCTRL 1 sudo bash /etc/triggerhappy/triggers.d/scale_left.sh?

**Comment by dooklink** [comment]
Yes very much so, Thankyou. I've only ever used left ctrl it seems.
This might have to go into v0.3, which may be a while off.

**Comment by HBDK** [comment]
yeah i was honestly surprised to see that you could use the right ctr...
